---
ansible_python_interpreter: /usr/bin/python3
ansible_connection: ssh
ansible_ssh_common_args: "-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o ServerAliveInterval=30"
local_user: "{{ lookup('env','USER') }}"
local_home: "{{ lookup('env','HOME') }}"
ansible_user:            "{{ deployment_user }}"
ansible_ssh_pass:        "{{ deployment_password }}"
ansible_become_password: "{{ deployment_password }}"
ssh_key_type: ed25519
  # rsa is not recognized for host signed cert in Ubuntu 20.04
  # ed25519 is the new fashionable replacement for rsa
ssh_host_key:          ssh_host_{{ ssh_key_type }}_key
ssh_host_key_pub:      ssh_host_{{ ssh_key_type }}_key.pub
ssh_host_key_pub_cert: ssh_host_{{ ssh_key_type }}_key-cert.pub
user_key:          id_{{ ssh_key_type }}
user_key_pub:      id_{{ ssh_key_type }}.pub
user_key_pub_cert: id_{{ ssh_key_type }}-cert.pub
ca_user_key:       ca_user_{{ ssh_key_type }}_key
ca_user_key_pub:   ca_user_{{ ssh_key_type }}_key.pub
ca_host_key:       ca_host_{{ ssh_key_type }}_key
ca_host_key_pub:   ca_host_{{ ssh_key_type }}_key.pub
ssh_dir: /home/{{ deployment_user }}/.ssh
keys_dir: /home/{{ deployment_user }}/keys
