---
all:
  vars:
    deployment_user: rasputin
    deployment_password: rasputin
  children:
    ca_host:
      hosts:
        raspberry3-wifi:
    deployment_hosts:
      hosts:
        raspberry1-wifi:
        raspberry2-wifi:
        raspberry3-wifi:
