---
- hosts: raspberry_wifis
  gather_facts: False
  tasks:
    #- name: role make_clean
      #include_role:
        #name: make_clean
    - name: fetch /etc/ssh/{{ ssh_host_key_pub }}
      fetch:
        src: /etc/ssh/{{ ssh_host_key_pub }}
        dest: fetch/host_public_keys/{{ inventory_hostname }}/{{ ssh_host_key_pub }}
        flat: yes
- hosts: ca_host
  gather_facts: True   # we need to gather facts
  tasks:
    - name: ssh_ca roles
      include_role:
        name: "{{ item }}"
      loop:
        - ssh_ca_user
        - ssh_ca_host
- hosts: raspberry_wifis
  gather_facts: False
  tasks:
    - name: various roles
      include_role:
        name: "{{ item }}"
      loop:
        - trust_user_ca_key
        - authorized_principals
        - host_certificate

  

