---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: ssh-keygen -t {{ ssh_type }} -f ~/.ssh/{{ user_key }}
      openssh_keypair:
        path: "{{ local_home }}/.ssh/{{ user_key }}"
        type: "{{ ssh_key_type }}"
- hosts: deployment_hosts
  gather_facts: False
  tasks:
    - name: fetch /etc/ssh/{{ ssh_host_key_pub }}
      fetch:
        src: /etc/ssh/{{ ssh_host_key_pub }}
        dest: fetch/host_public_keys/{{ inventory_hostname }}/{{ ssh_host_key_pub }}
        flat: yes
- hosts: ca_host
  gather_facts: True   # we need to gather facts
  tasks:
    - name: ssh_ca roles
      include_role:
        name: "{{ item }}"
      loop:
        - ssh_ca_user
        - ssh_ca_host
- hosts: deployment_hosts
  gather_facts: False
  tasks:
    - name: various roles
      include_role:
        name: "{{ item }}"
      loop:
        - trust_ca_user
        - authorized_principals
        - host_certificate
- hosts: localhost
  gather_facts: False
  tasks:
    - name: trust_ca_host
      include_role:
        name: trust_ca_host
    - name: test the login with unix noop ':'
      shell:
        cmd: |
          ssh \
            -o BatchMode=yes \
            -o IdentitiesOnly=yes \
            {{ local_user }}@{{ host }} \
            :
      changed_when: false
      loop: "{{ groups['deployment_hosts'] }}"
      loop_control:
        loop_var: host


